### ISSUE TITLE
NIEM subsets aren't conformant

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#10]
Migrated from NIEM/NIEM-NDR#107

Missing definitions and augmentation points cause NIEM subsets to throw conformance errors.  Should the SSGT change the `conformanceTarget` to `EXT`?  Should something else be done?

Jim Cabral: We used to have a subset as a conformance target

#resolved Go back to a Subset target

**Comment by cdmgtri** [comment]
Discussed again during the Nov 8, 2022 NTAC meeting. Adding a new conformance target would be a lot of work for not a lot of gain. Generating subsets with the EXT target would solve the missing augmentation point error. Most subsets are generated with definitions, which is preferred.

Will revisit this issue again later after further consideration, but the NTAC is currently leaning towards generating subsets as EXTs.

**Comment by cabralje** [comment]
We discussed again on 6/20/2023 and agreed to define a new conformance target to subsets of the NIEM reference schemas.

**Comment by iamdrscott** [comment]
Handled in NDR6.
