### ISSUE TITLE
Do not allow elements and attributes with the same uncased name

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#11]
Migrated from NIEM/NIEM-NDR#106 

New NDR rule.  Casing will be different due to current rules, but do not allow elements and attributes in the same namespace to have the same name.  This causes problems in case-insensitive environments.

Dr. Scott: Same _uncased_ name. Is there a rule between elements in the same namespace?

#todo Christina and Tom Carlson draft a rule for this.

**Comment by cdmgtri** [comment]
Schematron rule: For each attribute, do an uncased search for an element with the same name.

**Comment by iamdrscott** [comment]
Implemented with new rule 7-1 in section 7.1
