### ISSUE TITLE
Require definitions for patterns

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#12]
Migrated from NIEM/NIEM-NDR#111 

Definitions are required for enumeration facets only. Would also require definitions for patterns to give people a general idea of what the pattern is doing (or meant to be doing).

#resolved do it

**Comment by cdmgtri** [comment]
Definition from ANSI NIST ITL for biom:LipPatternSimpleType `<>`: Indicator for center of the lip (left < followed by right >)

**Comment by cdmgtri** [comment]
The Harmonization Subcommittee approved the following pattern definitions:

Type | Pattern | Definition
---- | ------- | ----------
ag_codes:TaxIdentificationIDSimpleType | `[0-9]{9}` | A 9-digit number
ag_codes:CropYearSimpleType | `^([1][9]\d\d\|[2]\d\d\d)$` | A 4-digit year ranging from 1900 to 2999.
mo:MILSTD2525-C-SIDC-SimpleType | `[A-Z0-9\-]{15}` | A 15-character ID with upper case letters, numbers, and hyphens
mo:MILSTD2525-B-SIDC-SimpleType | `[A-Z0-9\-]{15}` | A 15-character ID with upper case letters, numbers, and hyphens

See #58 for harmonizing the two MilOps SIDC types.

**Comment by cdmgtri** [comment]
Model changes merged into the dev branch for 6.0.

**Comment by iamdrscott** [comment]
Looks like all the patterns in PS01 have data definitions, so I added this rule to section 7.2.1 in NDR6
