### ISSUE TITLE
Do not allow niem.gov URIs in EXTs?

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#13]
Migrated from NIEM/NIEM-NDR#110 

New rule to try to make sure people don't use NIEM's `http:release.niem.gov/niem` URI for their target namespaces?  Make it invalid for EXTs?

But maybe we get into trouble if NIEM starts publishing IEPDs?  Although we could use a different path. That's what the `/niem` is there for, after all.

Jim Cabral: Expand to just `niem.gov`

Rules about these to allow them to be easily parsed, but disallowing "release.niem.gov" already does it.

No hash marks in the URI is already a rule in the IEPD spec.

#todo Add it to the NDR, and update how to qualify the URI section.

#resolved do it

**Comment by iamdrscott** [comment]
Well, "niem.gov" isn't right any more.  I decided to subsume this into a new rule that says namespace authors MUST own the namespace URI, as defined by [W3C web architecture](https://www.w3.org/TR/webarch/).  Implemented in section 8, rule 8-2.
