### ISSUE TITLE
Get rid of `structures:sequenceID`

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#19]
Migrated from NIEM/NIEM-NDR#103 

Replace `structures:sequenceID` with an appinfo element that marks it as sorted, for multiple elements.

It's an XML kludge that doesn't translate well to other things.

Dr. Scott: Could maybe in the future use JSON-LD instead of RDF?

_Are there environments in which the ordering isn't maintained?_

Mike Hulme: Can just be a business rule, too. Can maybe just get rid of the whole concept?

JSON Type Definition RFC 8923? Translates JSON Schema to all sort of other things.

Model Instance -> JSON TypeDef -> All sorts of stuff.

**Comment by cdmgtri** [comment]
Model changes merged into the dev branch.

**Comment by iamdrscott** [comment]
Done in PS01.
