### ISSUE TITLE
Support external attributes

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#20]
Migrated from NIEM/NIEM-NDR#117 

The adapter mechanism works by wrapping a single external element in a complex NIEM adapter type.  This solution does not work well for external attributes, especially if multiple attributes should be used together.

**Comment by cdmgtri** [comment]
See the [Attribute Augmentations](https://github.com/niemopen/ntac-admin/blob/main/documents/AttributeAugmentations-230118.md) writeup for potential attribute wildcards.

**Comment by iamdrscott** [comment]
NDR5 allows external attributes on conforming CCC types in extension schema documents; no adapter type required.  See section 10.2.3.3.  Preserved in NDR6; see section 9.8, rule 9-84.
