### ISSUE TITLE
metadata vs relationship metadata

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#21]
Migrated from NIEM/NIEM-NDR#101 

Clark Kent is the example.

The name isn't secret, but the relationship is.

#resolved Kill off `relationshipMetadata`. Let users implement if they really need that.

Dr. Scott looking at how this fits into JSON and RDF.

**Comment by iamdrscott** [comment]
Described in NDR6 PSD01 [section 5.5, Relationship properties](https://niemopen.github.io/niem-naming-design-rules/ndr-v6.0-psd01.html#55-relationship-properties).
