### ISSUE TITLE
xs:anyURI values must be valid

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#23]
Migrated from NIEM/NIEM-NDR#119 

XML Schema validation will pass almost any value in an element or attribute of type xs:anyURI. This of course means that some message will eventually contain XML like `<my:Thing structures:uri="boogla">`, for which there is no equivalent RDF, So I think we will need a rule in NDR 6, something like:

> The value of an element or attribute of type xs:anyURI MUST match the production or the production < "#" fragment> as defined by RFC 3986.

**Comment by iamdrscott** [comment]
Implemented in section 12, rule 12-11.
