### ISSUE TITLE
Conforming namespaces should declare their prefix

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#24]
Migrated from NIEM/NIEM-NDR#120 

Turns out that while a conforming schema document must declare targetNamespace, it does not have to declare a namespace prefix for that namespace URI. But CMF depends on a prefix for every namespace, and when CMFTool makes one up from whole cloth, it usually looks stupid. So I want a new NDR to say every conforming schema document must declare a prefix for the target namespace URI -- and furthermore, must not use "cmf", "rdf", "rdfs", "owl", "xs", or "xsd".

**Comment by iamdrscott** [comment]
Implemented in section 8.1, rule 8-3
