### ISSUE TITLE
Publish NDR 6.0 WD01

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#32]
Target deadline for NDR 6.0 Working Draft 01

- [x] Convert working files from XML to markdown
- [ ] Split generic model information from the XML-specific representation
- [ ] Reorganize into [new sections](https://github.com/niemopen/ntac-admin/discussions/42)
- [ ] Update the [principles section](https://github.com/niemopen/ntac-admin/discussions/38)
- [ ] Update `structures.xsd`
- [ ] Update `appinfo.xsd`
- [ ] Update Schematron rules

**Comment by iamdrscott** [comment]
PSD01 pushed to main branch today!
