### ISSUE TITLE
Drop attributes from structures:SimpleObjectAttributeGroup

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#33]
Consider dropping the following attributes from `structures:SimpleObjectAttributeGroup` to simplify data properties and datatypes:

| Attribute | Reason |
|:--------- |:------ |
| `structures:id` | IDs and references are typically used for objects, not literals
| `structures:ref` | (see above)
| `structures:uri` | Linked data is for object resources, not literals
| `structures:relationshipMetadata` | Use `structures:metadata` or attribute wildcards instead

**Comment by iamdrscott** [comment]
Partially done in PS01 -- we kept id, ref, and uri, dropped relationshipMetadata.
