### ISSUE TITLE
Do not allow multiple augmentations from the same namespace on the same object

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-naming-design-rules#35]
An augmentation is a container that lets us plug additional properties into existing types from other namespaces - types that we cannot modify ourselves.  These containers on their own have no meaning, and they do not appear in the NIEM RDF or NIEM JSON-LD representations.  Because they have no meaning on their own and because we would not be able to reconstruct them when transforming from NIEM RDF or NIEM JSON to NIEM XML, we should prohibit multiple augmentations from the same namespace on the same object.  

**Valid example:**

nc:PersonType
- nc:PersonName
- j:PersonAugmentation
- hs:PersonAugmentation
- biom:PersonAugmentation

**Invalid example:**

nc:PersonType
- nc:PersonName
- j:PersonAugmentation
- j:PersonAugmentation (*)
- j:PersonAugmentation (*)
- hs:PersonAugmentation
- biom:PersonAugmentation

_*: Justice person augmentation properties should be consolidated under a single `j:PersonAugmentation` container._

**Comment by cdmgtri** [comment]
This could be a new Schematron instance rule.

**Comment by iamdrscott** [comment]
Implemented as Rule 12-11 in NDR6.
